<br />
<br />

<form method="POST">

    <label for="phone_number">Phone number</label>
    <input id="phone_number" name="phone_number" type="text"><br />

    <label for="adress">Adress</label>
    <input id="adress" name="adress" type="text"><br />

    <label for="owner">Owner</label>
    <input id="owner" name="owner" type="text"><br />

    <label for="sum">Sum</label>
    <input id="sum" name="sum" type="text"><br />

    <label for="score">Score</label>
    <input id="score" name="score" type="text"><br />

    <button type="submit">Add</button>
</form>